### ISSUE TITLE
werf.yaml: check mounts

### ISSUE THREAD

**Issue by juev** [deckhouse/dmt#59]
In all werf files, check that if the image is using `BASE_GOLANG_*`, then there are options:

```
mount:
- fromPath: ~/go-pkg-cache
  to: /go/pkg
- from: tmp_dir
  to: /root/.cache/go-build
```
